// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp90TJV_DCBedelGytT4TFVh-1ONd-3jo',
    appId: '1:671517126615:web:6de036455fa8073a2fa592',
    messagingSenderId: '671517126615',
    projectId: 'atendimento-ti-super-9b426',
    authDomain: 'atendimento-ti-super-9b426.firebaseapp.com',
    storageBucket: 'atendimento-ti-super-9b426.firebasestorage.app',
    measurementId: 'G-26J5BWEVG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr_g1PAcGlqi7arLmVOiNYwERuA-hNmdE',
    appId: '1:671517126615:android:519b563cb2373a6e2fa592',
    messagingSenderId: '671517126615',
    projectId: 'atendimento-ti-super-9b426',
    storageBucket: 'atendimento-ti-super-9b426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC80y_E08sDAjdkHvwyqCF9pebwY9u_g-I',
    appId: '1:671517126615:ios:b3b86145d4243deb2fa592',
    messagingSenderId: '671517126615',
    projectId: 'atendimento-ti-super-9b426',
    storageBucket: 'atendimento-ti-super-9b426.firebasestorage.app',
    iosBundleId: 'com.example.atendimentoTiSeduc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC80y_E08sDAjdkHvwyqCF9pebwY9u_g-I',
    appId: '1:671517126615:ios:b3b86145d4243deb2fa592',
    messagingSenderId: '671517126615',
    projectId: 'atendimento-ti-super-9b426',
    storageBucket: 'atendimento-ti-super-9b426.firebasestorage.app',
    iosBundleId: 'com.example.atendimentoTiSeduc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp90TJV_DCBedelGytT4TFVh-1ONd-3jo',
    appId: '1:671517126615:web:0f773cc2ce72d72c2fa592',
    messagingSenderId: '671517126615',
    projectId: 'atendimento-ti-super-9b426',
    authDomain: 'atendimento-ti-super-9b426.firebaseapp.com',
    storageBucket: 'atendimento-ti-super-9b426.firebasestorage.app',
    measurementId: 'G-7N3HNBW9KV',
  );
}