name: atendimento_ti_seduc
description: "A new Flutter project."
publish_to: 'none'

# Ajuste a versão conforme necessário para seu próximo release
version: 2.0.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_storage: ^12.4.5
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  intl: ^0.19.0
  # auto_updater: ^1.0.0 # <<< REMOVIDO >>>
  signature: ^6.0.0 # Mantido para assinatura no perfil
  pdf: ^3.10.8
  path_provider: ^2.1.3
  share_plus: ^11.0.0
  open_filex: ^4.4.0
  audioplayers: ^6.0.0
  table_calendar: ^3.1.1
  # --- NOVAS DEPENDÊNCIAS PARA OPÇÃO 1 DE UPDATE ---
  http: ^1.1.0          # Ou versão mais recente (para buscar JSON)
  package_info_plus: ^8.3.0 # Ou versão mais recente (para pegar versão atual)
  url_launcher: ^6.3.1   # Ou versão mais recente (para abrir link download)
  pub_semver: ^2.1.4      # Ou versão mais recente (para comparar versões)
  printing: ^5.12.0
  image_picker: ^1.1.2
  # -------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Use a versão mais recente compatível
  msix: ^3.16.9

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #   # ...

msix_config:
  display_name: Atendimento TI SEDUC
  publisher_display_name: Sua Organização ou Nome
  publisher: CN=AtendimentoTISUPERTeste
  identity_name: SeuDominio.AtendimentoTISeduc
  msix_version: 2.0.2.1 # Deve corresponder à 'version' acima (ex: 2.0.0+1 -> 2.0.0.1)
  logo_path: assets/images/seu_logo.png # Caminho RELATIVO é recomendado
  certificate_path: C:\Users\Comum\Documents\GitHub\AtendimentoTISUPER\certificado_teste.pfx # <-- CUIDADO: Caminho absoluto. Relativo é melhor (ex: certs/certificado_teste.pfx)
  certificate_password: 100senha