name: atendimento_ti_seduc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0.0 # <-- Ajuste conforme sua versão atual

environment:
  sdk: '>=3.0.0 <4.0.0' # <-- Use um range mais flexível ou a sua versão exata

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_storage: ^12.4.5 # Versão verificada
  firebase_core: ^3.13.0    # Versão verificada
  cloud_firestore: ^5.6.7  # Versão verificada
  firebase_auth: ^5.5.3   # Versão verificada
  intl: ^0.19.0           # Use a versão mais recente compatível
  auto_updater: ^1.0.0      # Use a versão mais recente compatível
  signature: ^6.0.0         # Use a versão mais recente compatível
  pdf: ^3.10.8              # Use a versão mais recente compatível
  path_provider: ^2.1.3     # Use a versão mais recente compatível
  share_plus: ^11.0.0        # Use a versão mais recente compatível
  open_filex: ^4.4.0        # Use a versão mais recente compatível
  audioplayers: ^6.0.0        # Verifique a versão compatível
  table_calendar: ^3.1.1    # Verifique a versão compatível
  # msix: ^3.16.9 # Movido para dev_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Use a versão mais recente compatível
  msix: ^3.16.9 # Pacote para criar MSIX é uma dependência de desenvolvimento

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #   # ... (configuração de fontes)

# --- ADICIONE A CONFIGURAÇÃO MSIX AQUI ---
msix_config:
  display_name: Atendimento TI SEDUC # Nome que aparece para o usuário
  publisher_display_name: Sua Organização ou Nome # Nome do publicador que aparece
  publisher: CN=AtendimentoTISUPERTeste # IMPORTANTE: ID do Publicador. Para testes, use "CN=Teste". Para produção, use EXATAMENTE o "Subject" do seu certificado de assinatura (ex: "CN=Sua Empresa LTDA, O=Sua Empresa LTDA, L=Sua Cidade, S=Seu Estado, C=BR")
  identity_name: SeuDominio.AtendimentoTISeduc # Identificador único, geralmente no formato reverso de domínio
  msix_version: 1.0.0.2 # Versão do MSIX (deve ter 4 partes: Major.Minor.Build.Revision). Incremente a cada build. Pode basear-se na 'version' acima (ex: 1.0.0+1 -> 1.0.0.1)
  logo_path: assets/images/seu_logo.png # << CAMINHO RELATIVO para o logo (ex: dentro da pasta assets). Use barras normais '/'
  # capabilities: internetClient # Adicione capabilities necessárias (ex: acesso à internet)
  # languages: # Opcional: Especifique idiomas suportados
  #   - pt-br
  # architecture: x64 # Opcional: Especifique arquitetura (x64, arm64)
  certificate_path: C:\Users\Lenovo\Documents\GitHub\AtendimentoTISUPER\certificado_teste.pfx # Opcional: Caminho para o certificado .pfx para assinar
  certificate_password: 100senha # Opcional: Senha do certificado
# --- FIM DA CONFIGURAÇÃO MSIX ---